name: E2E Tests - Runs Arts QA

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # Removemos as linhas de cache por enquanto para não travar o log

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180 # Aumentei o tempo porque o Next.js pode demorar a subir no servidor do GitHub